### ISSUE TITLE
Test commented out is confusing 

### ISSUE THREAD

**Issue by ville144** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#7] opened 2022-04-12 02:44 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5282/assignments/162818?module_item_id=349443

### Concern

At start of lab the tests are commented out and   nowhere in the read.me does it say to uncomment. That was very confusing to me and multiple students

Written with the help of TC Johnathan Chriest

### Suggested Changes

Uncomment tests from start of lab.

**Comment by professor-ben** [comment] 2022-04-15 15:10
Hello,

I've taken a look at a few different versions / branches of this repo and I'm not seeing that the tests are commented out. Is it possible that you were working in a different repo?

Thanks,
Ben

**Comment by professor-ben** [comment] 2022-04-25 18:19
Hello again,

I talked a bit with some other people who saw this issue (including Johnathan) and I haven't been able to reproduce it myself. Johnathan mentioned that some new students who worked on it did not experience the issue either.

While I'm confident that something happened here, I'm going to close this for now since we haven't been able to reproduce it on our end. If anything similar happens, please let us know and we'll reopen this alongside the new issue.

Thanks,
Ben

**Closed as completed by professor-ben** 2022-04-25 18:19 UTC
Labels: se curriculum

**Comment by ville144** [comment] 2022-04-25 18:59
Thank you for looking into this matter
